site_name: volcGIS
site_url: https://vharg.github.io/VolcGIS/
repo_url: https://github.com/vharg/VolcGIS
repo_name: vharg/VolcGIS

theme:
  name: material
  # features:
  #     - navigation.tabs
  #     - navigation.sections
  #     - navigation.expand
  icon:
    repo: fontawesome/brands/github
  palette:
    - scheme: default
      accent: deep orange
      primary: blue grey
      toggle:
        icon: material/weather-sunny
        name: Switch to dark mode
    - scheme: slate
      accent: deep orange
      primary: blue grey
      toggle:
        icon: material/weather-night
        name: Switch to light mode

nav:
  - Home: index.md
  - Demo: MASTER_example.py
  - Changelog: changelog.md
  - Tips: tips.md
  - volcGIS API:
    - Module eruption: volcGIS_eruption.md
    - Module exposureAnalysis: volcGIS_exposureAnalysis.md

plugins:
    - search
    - mkdocstrings
    - mkdocs-jupyter:
        execute: True
        include_source: True

markdown_extensions:
  - pymdownx.highlight
  - pymdownx.superfences

extra:
  social:
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/VolcanoRisk
    - icon: fontawesome/brands/github
      link: https://github.com/vharg

extra_css:
  - stylesheets/extra.css